services:
  gello:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: gello_run
    privileged: true
    network_mode: host
    environment:
      USER: ${USER}
      QT_X11_NO_MITSHM: 1
      DISPLAY: $DISPLAY
      ROS_DOMAIN_ID: 42
    volumes:
      - ../gello_software:/gello
      - /dev/serial/by-id/:/dev/serial/by-id/
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: bash -c "pip install -e third_party/DynamixelSDK/python && exec bash"
    stdin_open: true
    tty: true
